name: gimmel
version: 0.4.0.0
github: "maxdeliso/gimmel"
license: MIT
author: "Max DeLiso"
maintainer: "me@maxdeliso.name"
copyright: "2020 Joseph Maximilian DeLiso"

extra-source-files:
  - README.md

description: UDP chat server

dependencies:
  - base>=4.18.2.1
  - optparse-applicative>=0.18.1.0
  - containers>=0.6.7
  - stm>=2.5.1.0
  - network>=3.1.4.0
  - aeson>=2.1.2.1
  - bytestring>=0.11.5.3
  - vty>=5.38
  - vty-crossplatform>=0.2.0.0
  - brick>=0.70.0
  - microlens>=0.4.13.0
  - microlens-th>=0.4.3.17
  - mtl>=2.3.1
  - monad-logger>=0.3.40
  - fast-logger>=3.1.0
  - text>=2.0.0
  - unliftio-core>=0.2.1.0
  - async>=2.2.5

executables:
  gimmel-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
  test-net:
    main: TestNet.hs
    source-dirs:
      - app
      - test
    other-modules:
      - Message
      - MonadNet
      - Net
      - Options
      - TUI
    ghc-options:
      - -threaded
      - -rtsopts

when:
  - condition: os(windows)
    dependencies:
      - Win32
  - condition: "!os(windows)"
    dependencies:
      - unix
