name: gimmel
version: 0.2.0.4
github: "maxdeliso/gimmel"
license: MIT
author: "Max DeLiso"
maintainer: "me@maxdeliso.name"
copyright: "2020 Joseph Maximilian DeLiso"

extra-source-files:
  - README.md

description: UDP chat server

dependencies:
  - base>=4.18.2.1
  - optparse-applicative>=0.18.1.0
  - containers>=0.6.7
  - stm>=2.5.1.0
  - network>=3.1.4.0
  - aeson>=2.1.2.1
  - bytestring>=0.11.5.3
  - vty>=5.38
  - vty-crossplatform>=0.2.0.0

executables:
  gimmel-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
