name: gimmel
version: 0.2.0.3
github: "maxdeliso/gimmel"
license: MIT
author: "Max DeLiso"
maintainer: "me@maxdeliso.name"
copyright: "2020 Joseph Maximilian DeLiso"

extra-source-files:
  - README.md

description: UDP chat server

dependencies:
  - base>=4
  - optparse-applicative>=0.17
  - containers>=0.6
  - stm>=2.5
  - network>=3.1
  - aeson>=2.0
  - bytestring>=0.11

executables:
  gimmel-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
