name: Haskell CI

on: [push]

jobs:
  runhaskell:
    name: Stack build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v1.1
        with:
          ghc-version: "9.2.5"
          enable-stack: true
          stack-version: "latest"
      - run: stack build

permissions:
  contents: read
